# Generated by Django 5.0.2 on 2024-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTraining', models.DateField()),
                ('hourOfTraining', models.TimeField()),
                ('trainingDuration', models.IntegerField()),
                ('typeOfWorkout', models.CharField(choices=[('no-gi', 'NO-GI'), ('gi', 'GI')], max_length=5)),
                ('howManyFights', models.IntegerField()),
                ('fightDuration', models.IntegerField()),
                ('breakDuration', models.IntegerField()),
                ('tiredAfter', models.IntegerField()),
                ('injuriesAfter', models.CharField(max_length=10)),
            ],
        ),
    ]
