# Generated by Django 5.0.2 on 2024-03-03 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_trening_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zawody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfComp', models.CharField(max_length=20)),
                ('dateOfComp', models.DateField()),
                ('place', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompFight',
            fields=[
                ('compFight_id', models.AutoField(primary_key=True, serialize=False)),
                ('resultOfFight', models.CharField(choices=[('Win', 'W'), ('Lose', 'L')], max_length=10)),
                ('endOfFight', models.CharField(choices=[('Submission', 'SUB'), ('Points', 'PO'), ('Disqualification', 'DQ'), ('Choice', 'CHO')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compFight', to=settings.AUTH_USER_MODEL)),
                ('whichComp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='mainSite.zawody')),
            ],
        ),
    ]
